runtime: python # qual é a linguegem que estamos usando 
env: flex # qual é o ambiente do App Engine que vamos usar, fls ou standard?
entrypoint: gunicorn -b :$PORT main:app # Como vou startar minha aplicação?

runtime_config:
    python_version: 3

includes:
- env_vars.yaml